# Generated by Django 4.2.13 on 2024-09-20 15:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_member',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholdere', max_length=255, verbose_name='image'),
        ),
    ]
