# Generated by Django 4.2.13 on 2024-09-20 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
