# Generated by Django 4.2.13 on 2024-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_member',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
