# Generated by Django 4.2.13 on 2026-09-14 18:49

import cloudinary.models
from django.db import migrations
import staff.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_member_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, validators=[staff.validators.validate_file_size], verbose_name='image'),
        ),
    ]
