# Generated by Django 4.2.13 on 2024-09-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='author',
            new_name='user',
        ),
    ]
