# Generated by Django 4.2.13 on 2024-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='content',
            field=models.TextField(default='blank'),
        ),
    ]
