# Generated by Django 4.2.13 on 2024-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
