# Generated by Django 4.2.13 on 2024-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussion_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_on']},
        ),
    ]
