# Generated by Django 4.2.13 on 2024-09-20 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_alter_discussion_content_alter_discussion_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
