# Generated by Django 4.2.13 on 2024-09-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_discussion_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='updated_on',
        ),
    ]
