# Generated by Django 4.2.13 on 2024-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_remove_comment_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
